# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business_type', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4)], default=1)),
            ],
            options={
                'verbose_name_plural': 'Businesses',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Business')),
            ],
        ),
        migrations.CreateModel(
            name='GenericModelA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Generic Model A's",
            },
        ),
        migrations.CreateModel(
            name='GenericModelB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': "Generic Model B's",
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter the name of the staff being rounded', max_length=255)),
                ('last_name', models.CharField(help_text='Enter the name of the staff being rounded', max_length=255)),
                ('active', models.CharField(choices=[(b'active', b'Active'), (b'inactive', b'Inactive'), (b'terminated', b'Terminated')], max_length=10)),
                ('is_manager', models.BooleanField(default=False)),
                ('date_hired', models.DateTimeField(default=staff.models.add_a_datetime)),
                ('last_incident', models.DateField(default=staff.models.add_a_date)),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.ContractType')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Department')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Position')),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
                'verbose_name_plural': 'staff',
            },
        ),
    ]
