# Generated by Django 4.1 on 2023-04-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='generic_object_multi',
            field=models.ManyToManyField(blank=True, related_name='generic_object_multi', to='staff.genericmodelb'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated')], max_length=10),
        ),
        migrations.AlterField(
            model_name='staff',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'staff'), ('model', 'genericmodela')), models.Q(('app_label', 'staff'), ('model', 'genericmodelb')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
